In [2]:
from alpha_vantage.timeseries import TimeSeries
import pandas as pd

api_key = 'LLSGCNAU6ZQMK8KL'
ts = TimeSeries(key=api_key, output_format='pandas')

# Get daily prices for Apple
data, meta_data = ts.get_daily(symbol='AAPL', outputsize='full')
data = data.sort_index()  # Ensure data is in ascending order by date



In [3]:
df=pd.DataFrame(data)
df.columns = ['Open', 'High', 'Low', 'Close', 'Volume']
df

Open     High     Low   Close       Volume
date                                                     
1999-11-01   80.000   80.690   77.37   77.62    2487300.0
1999-11-02   78.000   81.690   77.31   80.25    3564600.0
1999-11-03   81.620   83.250   81.00   81.50    2932700.0
1999-11-04   82.060   85.370   80.62   83.62    3384700.0
1999-11-05   84.620   88.370   84.00   88.31    3721500.0
...             ...      ...     ...     ...          ...
2025-07-28  214.030  214.845  213.06  214.05   37858017.0
2025-07-29  214.175  214.810  210.82  211.27   51411723.0
2025-07-30  211.895  212.390  207.72  209.05   45512514.0
2025-07-31  208.490  209.840  207.16  207.57   80698431.0
2025-08-01  210.865  213.580  201.50  202.38  104434473.0

[6477 rows x 5 columns]

In [ ]:
import numpy as np
X=np.array(df)


In [9]:
X_centered = X - np.mean(X, axis=0)
X_centered

array([[-9.56303428e+01, -9.68896179e+01, -9.62260260e+01,
        -9.80286257e+01, -3.12711724e+07],
       [-9.76303428e+01, -9.58896179e+01, -9.62860260e+01,
        -9.53986257e+01, -3.01938724e+07],
       [-9.40103428e+01, -9.43296179e+01, -9.25960260e+01,
        -9.41486257e+01, -3.08257724e+07],
       ...,
       [ 3.62646572e+01,  3.48103821e+01,  3.41239740e+01,
         3.34013743e+01,  1.17540416e+07],
       [ 3.28596572e+01,  3.22603821e+01,  3.35639740e+01,
         3.19213743e+01,  4.69399586e+07],
       [ 3.52346572e+01,  3.60003821e+01,  2.79039740e+01,
         2.67313743e+01,  7.06760006e+07]])

In [12]:
U,s,Vt = np.linalg.svd(X_centered)
Vt.T[:,0]

array([ 1.65265249e-07,  1.56981703e-07,  1.74429985e-07,  1.65997774e-07,
       -1.00000000e+00])

In [13]:
from sklearn.decomposition import PCA
pca = PCA()
X_PCA = pca.fit_transform(X)

In [14]:
pca.components_.T[:, 0]

array([-1.65265249e-07, -1.56981703e-07, -1.74429985e-07, -1.65997774e-07,
        1.00000000e+00])

In [15]:
pca.explained_variance_ratio_

array([1.00000000e+00, 8.98820496e-11, 6.04768130e-15, 3.90775952e-15,
       6.76298446e-16])

In [17]:
np.round(pca.components_[0])

array([-0., -0., -0., -0.,  1.])